// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH_ZnNFBm5r9IHQjavgfdID04VDNn7xng',
    appId: '1:422635113271:web:6f3d2032b01aa7262568b2', // Update the appId.
    messagingSenderId: '422635113271', // Update the messagingSenderId.
    projectId:
        'linktopus-bfe2d', // Update the projectId to match the new project ID.
    authDomain:
        'linktopus-bfe2d.firebaseapp.com', // Update authDomain based on the project ID.
    storageBucket: 'linktopus-bfe2d.appspot.com', // Update the storageBucket.
    measurementId:
        'G-2VKVH47YP0', // MeasurementId for Google Analytics (if used).
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RuMZS-Rra16QUXsJ94D5d9XuMqSkWEw',
    appId: '1:422635113271:android:6f3d2032b01aa7262568b2', // Update the appId.
    messagingSenderId: '422635113271', // Update the messagingSenderId.
    projectId:
        'linktopus-bfe2d', // Update the projectId to match the new project ID.
    databaseURL:
        'https://linktopus-bfe2d-default-rtdb.firebaseio.com', // Update the databaseURL.
    storageBucket: 'linktopus-bfe2d.appspot.com', // Update the storageBucket.
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLKbN-TjmqOyc7qup7O3KaKbwYEmdB9c',
    appId: '1:422635113271:ios:6f3d2032b01aa7262568b2', // Update the appId.
    messagingSenderId: '422635113271', // Update the messagingSenderId.
    projectId:
        'linktopus-bfe2d', // Update the projectId to match the new project ID.
    databaseURL:
        'https://linktopus-bfe2d-default-rtdb.firebaseio.com', // Update the databaseURL.
    storageBucket: 'linktopus-bfe2d.appspot.com', // Update the storageBucket.
    iosClientId:
        '422635113271-r36b5ltsb93vo2j2q22hmulgo73bp8l6.apps.googleusercontent.com', // Update with your iOS client ID.
    iosBundleId: 'com.example.linktopusApp', // Update with your iOS bundle ID.
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLKbN-TjmqOyc7qup7O3KaKbwYEmdB9c',
    appId: '1:422635113271:ios:6f3d2032b01aa7262568b2', // Update the appId.
    messagingSenderId: '422635113271', // Update the messagingSenderId.
    projectId:
        'linktopus-bfe2d', // Update the projectId to match the new project ID.
    databaseURL:
        'https://linktopus-bfe2d-default-rtdb.firebaseio.com', // Update the databaseURL.
    storageBucket: 'linktopus-bfe2d.appspot.com', // Update the storageBucket.
    iosClientId:
        '422635113271-r36b5ltsb93vo2j2q22hmulgo73bp8l6.apps.googleusercontent.com', // Update with your iOS client ID.
    iosBundleId: 'com.example.linktopusApp', // Update with your iOS bundle ID.
  );
}
