// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH_ZnNFBm5r9IHQjavgfdID04VDNn7xng',
    appId: '1:972010493205:web:477d96951166c2221f451c',
    messagingSenderId: '972010493205',
    projectId: 'linktopus-abd56',
    authDomain: 'linktopus-abd56.firebaseapp.com',
    databaseURL: 'https://linktopus-abd56-default-rtdb.firebaseio.com',
    storageBucket: 'linktopus-abd56.appspot.com',
    measurementId: 'G-2VKVH47YP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RuMZS-Rra16QUXsJ94D5d9XuMqSkWEw',
    appId: '1:972010493205:android:8657cdb7fe9e3e6b1f451c',
    messagingSenderId: '972010493205',
    projectId: 'linktopus-abd56',
    databaseURL: 'https://linktopus-abd56-default-rtdb.firebaseio.com',
    storageBucket: 'linktopus-abd56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLKbN-TjmqOyc7qup7O3KaKbwYEmdB9c',
    appId: '1:972010493205:ios:20252e44d97b4f541f451c',
    messagingSenderId: '972010493205',
    projectId: 'linktopus-abd56',
    databaseURL: 'https://linktopus-abd56-default-rtdb.firebaseio.com',
    storageBucket: 'linktopus-abd56.appspot.com',
    iosClientId: '972010493205-h49u97g86n9in748jei2v6gu9bs27n40.apps.googleusercontent.com',
    iosBundleId: 'com.example.linktopusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLKbN-TjmqOyc7qup7O3KaKbwYEmdB9c',
    appId: '1:972010493205:ios:20252e44d97b4f541f451c',
    messagingSenderId: '972010493205',
    projectId: 'linktopus-abd56',
    databaseURL: 'https://linktopus-abd56-default-rtdb.firebaseio.com',
    storageBucket: 'linktopus-abd56.appspot.com',
    iosClientId: '972010493205-h49u97g86n9in748jei2v6gu9bs27n40.apps.googleusercontent.com',
    iosBundleId: 'com.example.linktopusApp',
  );
}
